development:
  adapter: postgresql
  encoding: utf8
  database: cg_client_track_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: cg_client_track_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: cg_client_track_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST